# EXERCICE : construirer une matrice A de taille (7x5) constituée de 4 blocs.

In [10]:
%display latex

Nous commençons par construire quatres blocs ou sous-matrices relativement à ce que nous voulons comme résultat.

In [11]:
A1 = 5*matrix.ones(3,2)
A2 = -2*matrix.ones(3,3)
A3 = 3*matrix.ones(5,2)
A4 = 4*matrix.ones(5,2)

On a donc les sous-matrices nommées A1, A2, A3 et A4.

In [12]:
A1

[5 5]
[5 5]
[5 5]

In [13]:
A2

[-2 -2 -2]
[-2 -2 -2]
[-2 -2 -2]

In [14]:
A3

[3 3]
[3 3]
[3 3]
[3 3]
[3 3]

In [15]:
A4

[4 4]
[4 4]
[4 4]
[4 4]
[4 4]

En augmentant la sous-matrice A2 sur la sous-matrice A1. On obtient une matrice qu'on a appelé A5.

In [16]:
A5 = A1.augment(A2)

In [17]:
A5

[ 5  5 -2 -2 -2]
[ 5  5 -2 -2 -2]
[ 5  5 -2 -2 -2]

La transposé de cette matrice A5 notée A6 nous conduit à une forme proche de celle de la matrice A recherchée.

In [18]:
A6 = A5.transpose()

In [19]:
A6

[ 5  5  5]
[ 5  5  5]
[-2 -2 -2]
[-2 -2 -2]
[-2 -2 -2]

Nous augmentons la sous-matrice A3 sur la matrice A6 et nous obtenons la matrice A7.

In [20]:
A7 = A6.augment(A3)

In [21]:
A7

[ 5  5  5  3  3]
[ 5  5  5  3  3]
[-2 -2 -2  3  3]
[-2 -2 -2  3  3]
[-2 -2 -2  3  3]

La matrice A7 obtenue est transposée avant qu'on y augemente la sous-matrice A4.

In [22]:
A8 = A7.transpose()

In [23]:
A9 = A8.augment(A4)

In [24]:
A9

[ 5  5 -2 -2 -2  4  4]
[ 5  5 -2 -2 -2  4  4]
[ 5  5 -2 -2 -2  4  4]
[ 3  3  3  3  3  4  4]
[ 3  3  3  3  3  4  4]

Nous obtenons donc notre matrice A recherchée qui est la transposée de la matrice A9.

In [25]:
A = A9.transpose()

In [26]:
A

[ 5  5  5  3  3]
[ 5  5  5  3  3]
[-2 -2 -2  3  3]
[-2 -2 -2  3  3]
[-2 -2 -2  3  3]
[ 4  4  4  4  4]
[ 4  4  4  4  4]